version: '2'
services:   
# THIS IS GEOSERVER (ASSUMES ZOOKEEPER, HADOOP + ACCUMULO IS UP)  
    geodocker-geoserver:
        image: ${PULL_PREFIX}/geodocker-geoserver
        hostname: geodocker-geoserver
networks:
  default:
    external:
      name: ${CLUSTER_NET}

