version: '2'
services:   
# THIS IS A FULL STACK (SHUT-DOWN ALL ELSE PRIOR)
# CAN START CORE FIRST, THEN START OTHERS INDIVIDUALLY
# e.g. `docker-compose -f core.yml up` then `docker-compose -f accumulo.yml up` etc.
    geodocker-zookeeper:
        image: ${PULL_PREFIX}/geodocker-zookeeper
        ports:
          - '2181:2181'                
    geodocker-hadoop-name:
        image: ${PULL_PREFIX}/geodocker-hadoop
        command: name dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
        ports:
          - '50070:50070'
        links:
          - geodocker-zookeeper
    geodocker-hadoop-sname:
        image: ${PULL_PREFIX}/geodocker-hadoop
        command: sname dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
        ports:
          - '50090:50090'
        links:
          - geodocker-hadoop-name
    geodocker-hadoop-data:
        image: ${PULL_PREFIX}/geodocker-hadoop
        command: data dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
        ports:
# The host port can be randomly assigned by Docker, to allow scaling to multiple DataNodes on the same host
# To enable, provide '<port>' instead of '<port>:<port>'
          - '50075:50075'
        links:
          - geodocker-hadoop-name
    geodocker-accumulo-master:
        # choose one of images (geodocker-accumulo-gis / geodocker-accumulo)
        image: ${PULL_PREFIX}/geodocker-accumulo-gis
        command: master dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: ${ACC_SECRET}
          ACCUMULO_PASSWORD: ${ACC_PWD}
          INSTANCE_NAME: gis
        volumes:
          - './accumulo/fs/sbin:/sbin:rw'
        depends_on:
          - geodocker-hadoop-data
    geodocker-accumulo-gc:
        # choose one of images (geodocker-accumulo-gis / geodocker-accumulo)
        image: ${PULL_PREFIX}/geodocker-accumulo-gis
        command: gc dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: ${ACC_SECRET}
          ACCUMULO_PASSWORD: ${ACC_PWD}
        depends_on:
          - geodocker-accumulo-master
    geodocker-accumulo-monitor:
      # choose one of images (geodocker-accumulo-gis / geodocker-accumulo)
        image: ${PULL_PREFIX}/geodocker-accumulo-gis
        command: monitor dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: ${ACC_SECRET}
          ACCUMULO_PASSWORD: ${ACC_PWD}
        ports:
          - '50095:50095'
        depends_on:
          - geodocker-accumulo-master
    geodocker-accumulo-tracer:
        # choose one of images (geodocker-accumulo-gis / geodocker-accumulo)
        image: ${PULL_PREFIX}/geodocker-accumulo-gis
        command: tracer dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: ${ACC_SECRET}
          ACCUMULO_PASSWORD: ${ACC_PWD}
        depends_on:
          - geodocker-accumulo-master
    geodocker-accumulo-tserver:
        # choose one of images (geodocker-accumulo-gis / geodocker-accumulo)
        image: ${PULL_PREFIX}/geodocker-accumulo-gis
        command: tserver dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: ${ACC_SECRET}
          ACCUMULO_PASSWORD: ${ACC_PWD}
        depends_on:
          - geodocker-accumulo-master
          - geodocker-accumulo-gc
          - geodocker-accumulo-monitor
          - geodocker-accumulo-tracer
    geodocker-spark-master:
        image: ${PULL_PREFIX}/geodocker-spark
        command: master dev
        hostname: geodocker-spark-master
        environment:
          SPARK_DAEMON_MEMORY: 2g
          SPARK_SUBMIT_DRIVER_MEMORY: 1g
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          MASTER: spark://geodocker-spark-master:7077
        ports:
          - 8080:8080        
        depends_on:
          - geodocker-hadoop-data
    geodocker-spark-worker:
        image: ${PULL_PREFIX}/geodocker-spark
        command: worker dev
        hostname: geodocker-spark-worker
        environment:
          SPARK_DAEMON_MEMORY: 2g
          SPARK_SUBMIT_DRIVER_MEMORY: 1g
          SPARK_WORKER_CORES: 8
          SPARK_WORKER_MEMORY: 16g
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          SPARK_MASTER: geodocker-spark-master
        depends_on:
          - geodocker-spark-master
    geodocker-geoserver:
        image: ${PULL_PREFIX}/geodocker-geoserver
        hostname: geodocker-geoserver            
        depends_on:
          - geodocker-accumulo-tserver
networks:
  default:
    external:
      name: ${CLUSTER_NET}

